baseURL = "https://dennytsai-arch.github.io/the-sloth/"
languageCode = "en-us"
title = "The Sloth"
theme = "PaperMod"
paginate = 10

[params]
  hideAuthor = true
  description = "Personal blog and notes"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  hideSummary = true

  [params.homeInfoParams]
    Title = "慢速前進的懶惰書店"
    Content = ""


[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Book"
    url = "/categories/book/"
    weight = 2
  [[menu.main]]
    name = "Exhibition"
    url = "/categories/exhibition/"
    weight = 3
  [[menu.main]]
    name = "Review"
    url = "/categories/review/"
    weight = 4
  [[menu.main]]
    name = "Design"
    url = "/categories/design/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 7

[outputs]
  home = ["HTML", "RSS", "JSON"]
