baseURL = "https://dennytsai-arch.github.io/the-sloth/"
languageCode = "en-us"
title = "The Sloth"
theme = "PaperMod"
paginate = 10

[params]
  hideAuthor = true
  description = "Personal blog and notes"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  hideSummary = true

  [params.homeInfoParams]
    Title = "緩慢前進的懶惰書店"
    Content = ""


[menu]
  [[menu.main]]
    name = "Book"
    url = "/categories/book/"
    weight = 2
    pre = '<span class="nav-cat-icon nav-cat-book"></span>'
  [[menu.main]]
    name = "Exhibition"
    url = "/categories/exhibition/"
    weight = 3
    pre = '<span class="nav-cat-icon nav-cat-exhibition"></span>'
  [[menu.main]]
    name = "Review"
    url = "/categories/review/"
    weight = 4
    pre = '<span class="nav-cat-icon nav-cat-review"></span>'
  [[menu.main]]
    name = "Design"
    url = "/categories/design/"
    weight = 5
    pre = '<span class="nav-cat-icon nav-cat-design"></span>'
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 7

[outputs]
  home = ["HTML", "RSS", "JSON"]
